spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/city_driver
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    time-zone: GMT-3
    date-format: yyyy-MM-dd
  mvc:
    locale: es
    locale-resolver: fixed

flyway:
  enabled: true
  baseline-version: 1
  schemas: public
  locations: classpath:db/migration
  sql-migration-suffixes: .sql
  baseline-on-migrate: true
  sql-migration-prefix: V

api:
  key:
    name: API_KEY
    value: fgfd1sdfg1513153&%&4@£dfsafsd32


